### PR TITLE
Fix NPE in validateArgumentTypes method

### LINKED ISSUE #106: NPE in validateArgumentTypes method
[2017-05-24 16:34:01,245] [EI-Core] ERROR - ServerWorker Error processing POST reguest for : /services/mydataservice/testpath. Error detail: null.
java.lang.NullPointerException
at org.apache.axis2.json.gson.GsonXMLStreamReader.validateArgumentTypes(GsonXMLStreamReader.java:783)
at org.apache.axis2.json.gson.GsonXMLStreamReader.nextValue(GsonXMLStreamReader.java:734)
at org.apache.axis2.json.gson.GsonXMLStreamReader.readValue(GsonXMLStreamReader.java:626)
at org.apache.axis2.json.gson.GsonXMLStreamReader.stateTransition(GsonXMLStreamReader.java:532)
at org.apache.axis2.json.gson.GsonXMLStreamReader.next(GsonXMLStreamReader.java:178)
at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
at org.apache.axiom.om.impl.llom.OMSerializableImpl.build(OMSerializableImpl.java:78)
at org.apache.axiom.om.impl.llom.OMElementImpl.build(OMElementImpl.java:722)
at org.apache.axiom.om.impl.llom.OMElementImpl.detach(OMElementImpl.java:700)
at org.apache.axiom.om.impl.llom.OMNodeImpl.setParent(OMNodeImpl.java:105)
at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:296)
at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:212)
at org.apache.axiom.soap.impl.llom.SOAPBodyImpl.addChild(SOAPBodyImpl.java:231)
at org.apache.axis2.json.gson.JSONMessageHandler.invoke(JSONMessageHandler.java:84)
at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by madhawa-gunasekara**
Resolves #106

### CODE REVIEW

File: modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java [hunk 1]
```diff
@@ -780,19 +780,20 @@ private String nextValue() {
...
             return true;
         } else if (tokenType == JsonToken.NULL) {
             return true;
         } else if (tokenType == JsonToken.NUMBER) {
-            if (expectedType.equals("int") || expectedType.equals("long") || expectedType.equals("double")
-                    || expectedType.equals("float") || expectedType.equals("decimal") || expectedType.equals("byte")
-                    || expectedType.equals("short")) {
+            if (expectedType != null && (expectedType.equals("int") || expectedType.equals("long")
+                    || expectedType.equals("double") || expectedType.equals("float") || expectedType.equals("decimal")
+                    || expectedType.equals("byte") || expectedType.equals("short"))) {
```
Comment (daneshk) [inline modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java]: shall we do the check like _"int".equals(expectedType)_ . So that we can avoid null check at the beginning.

Comment (madhawa-gunasekara) [inline modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java]: +1
